name: Sync & Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/NewMoe-Technology/cactbot.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit --strategy-option theirs

      - name: Push changes to origin
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TRIGGER_REPO_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main

      - uses: ./.github/actions/setup-js-env

      - name: Set artifact name
        shell: bash
        run: |
          sha=$(echo "${{ github.sha }}" | cut -c 1-8)
          echo "artifact_sha=$sha" >> $GITHUB_ENV

      - name: Check dependencies cache
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: ./plugin/ThirdParty
          key: |
            ${{ runner.os }}-cactbot-${{ hashFiles('./util/fetch_deps.ts', './util/DEPS.json5') }}
          restore-keys: |
            ${{ runner.os }}-cactbot-

      - name: Fetch dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm run fetch-deps

      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v3

      - name: Add Custom Problem Matcher
        run: echo "::add-matcher::.github/matchers/msbuild.json"

      - name: MSBuild
        run: msbuild /p:Configuration=Release /p:Platform=x64 plugin/Cactbot.sln
        shell: cmd

      - name: Build JavaScript UI Module Bundles
        run: npm run build
        timeout-minutes: 10

      - name: Generate artifact
        shell: bash
        run: ./util/publish.sh

      - name: Package cactbot release
        run: |
          cd publish
          7z a cactbot.zip cactbot-release/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.artifact_sha }}
          name: Release ${{ env.artifact_sha }}
          files: ./publish/cactbot.zip
          generate_release_notes: true
          make_latest: true
